#!/bin/bash

SYSFL=/etc/sysctl.d/10-tcp-buffers


cat << EOF > $SYSFL
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.ipv4.tcp_rmem = 4096 87380 16554432
net.ipv4.tcp_wmem = 4096 65536 16554432
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
EOF

/sbin/sysctl -p $SYSFL

